library(terra)
library(FactoMineR)
library(factoextra)
raster_folder <- choose.dir()
pearson_file <- choose.files()
pearson_list <- read.csv(pearson_file, stringsAsFactors = FALSE)
print(pearson_list)
all_layers <- list.files(raster_folder, pattern = "\\.asc$", full.names = TRUE)
set7 <- paste0(pearson_list$A, ".asc")
set8 <- paste0(pearson_list$B, ".asc")
print(set7)
filtered7 <- all_layers[basename(all_layers) %in% set7]
filtered8 <- all_layers[basename(all_layers) %in% set8]
rasters7 <- rast(filtered7)
rasters8 <- rast(filtered8)
prespoint <- choose.files()
presdata <- read.csv(prespoint)
env_values8 <- extract(rasters8, presdata[, c("LONG", "LAT")])
env8_matrix <- data.frame(presdata, env_values8)
nodata_matrix <- complete.cases(env8_matrix)
filtered_matrix <- env8_matrix[nodata_matrix, ]
pca_result <- PCA(filtered_matrix[, -c(1:4)], scale.unit = TRUE, ncp = 5, graph = TRUE)
fviz_pca_var(pca_result, col.var = "contrib")
hcpc_result <- HCPC(pca_result, graph = TRUE)
groups8 <- dimdesc(pca_result)
print(groups8)
write.csv()