library(terra)
folder_path <- choose.dir()
folder_path2 <- choose.dir()
raster_files <- list.files(folder_path, pattern = "\\.asc$", full.names = TRUE)
raster_stack <- rast(raster_files)
print(raster_stack)
system.time(cor_matrix <- layerCor(raster_stack, fun = "pearson"))
print(cor_matrix)
output_path <- file.path(folder_path2, "correlation_matrix.csv")
write.csv(cor_matrix, output_path, row.names = TRUE)
